version: '2'

services:

  mongo:
    image: mongo
    volumes:
     - ./data/db:/data/db
    expose:
    - 27017
    ports:
    - "27017:27017"
    hostname: mongo

  web:
    image: node:latest
    volumes:
     - .:/app
    working_dir: /app
    ports:
      - 4000:4000
      - 8080:8080
    command: sh -c "npm install --prefix ./client ; npm run --prefix ./client serve & npm install ; npm start"
    links:
    - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017